services:
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - postgres-db
    networks:
      - final-work-flow
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - final-work-flow
    volumes:
      - redis-data:/data
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: AutoX
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - salon-network
volumes:
  redis-data:
  postgres-data:
networks:
  final-work-flow:
    driver: bridge
    

